using RoR2;
using Nautilus.Configuration;
using System;
using R2API;
using UnityEngine;
using UnityEngine.AddressableAssets;
using HarmonyLib;
using UnityEngine.Networking;
using RoR2.Items;

namespace Nautilus.Items
{
    public static partial class ItemInit
    {
        public static MotherOfPearl MotherOfPearl = new MotherOfPearl
        (
            "MotherOfPearl",
            [ItemTag.Damage, ItemTag.AIBlacklist, ItemTag.ExtractorUnitBlacklist, ItemTag.BrotherBlacklist],
            ItemTier.VoidTier3
        );
    }

    /// <summary>
    ///     // Ver.1
    ///     A good compromise for a money item; old War Bonds sucked because the money didn't feel important for a legendary, but this item gives the player both money and damage
    ///     Synergizes with ICBM and pickup items like Ghor's Tome, so this can really pop off in the right circumstances
    ///     Tradeoff between direct boss damage w/ War Bonds, or this item's passive damage (and the potential downside of your pickups being turned to gold)
    /// </summary>
    public class MotherOfPearl : ItemBase
    {
        public override bool Enabled => MotherOfPearl_Enabled.Value;
        public override ItemDef ConversionItemDef => Addressables.LoadAssetAsync<ItemDef>("RoR2/DLC2/Items/BarrageOnBoss/BarrageOnBoss.asset").WaitForCompletion();
        public override GameObject itemPrefab => OverwritePrefabMaterials();
        public Material material0 => Addressables.LoadAssetAsync<Material>("RoR2/DLC1/voidstage/matVoidTerrain.mat").WaitForCompletion();
        public Material material1 => Addressables.LoadAssetAsync<Material>("RoR2/Base/BonusGoldPackOnKill/matTomeGold.mat").WaitForCompletion();
        public override Sprite itemIcon => Main.Assets.LoadAsset<Sprite>("Assets/icons/motherOfPearl.png");
        public static GameObject moneyPackPrefab => Addressables.LoadAssetAsync<GameObject>("RoR2/Base/BonusGoldPackOnKill/BonusMoneyPack.prefab").WaitForCompletion();
        public static GameObject convertEffectPrefab => Addressables.LoadAssetAsync<GameObject>("RoR2/Base/DeathProjectile/DeathProjectileTickEffect.prefab").WaitForCompletion();

        public MotherOfPearl(string _name, ItemTag[] _tags, ItemTier _tier, bool _canRemove = true, bool _isConsumed = false, bool _hidden = false) : 
        base(_name, _tags, _tier, _canRemove, _isConsumed, _hidden){}

        // Config
        public static ConfigItem<bool> MotherOfPearl_Enabled = new ConfigItem<bool>
        (
            "Void legendary: Mother Of Pearl",
            "Item enabled",
            "Should this item appear in runs?",
            true
        );
        public static ConfigItem<int> MotherOfPearl_MissilesLaunched = new ConfigItem<int>
        (
            "Void legendary: Mother Of Pearl",
            "Missiles launched",
            "How many missiles to launch on gold pickup",
            3,
            1f,
            10f,
            1f
        );
        public static ConfigItem<float> MotherOfPearl_DamageCoeff = new ConfigItem<float>
        (
            "Void legendary: Mother Of Pearl",
            "Missile damage",
            "Missile damage in percentage",
            300f,
            100f,
            1000f,
            100f
        );
        public static ConfigItem<float> MotherOfPearl_DamageCoeffStack = new ConfigItem<float>
        (
            "Void legendary: Mother Of Pearl",
            "Missile damage (per stack)",
            "Missile damage in percentage, per additional stack",
            300f,
            100f,
            1000f,
            100f
        );
        public static ConfigItem<float> MotherOfPearl_PickupConvert = new ConfigItem<float>
        (
            "Void legendary: Mother Of Pearl",
            "Gold convert chance",
            "Flat fractional chance for any pickup generated by the holder to convert into a gold chunk",
            0.1f,
            0f,
            1f,
            0.01f
        );
        public static ConfigItem<bool> MotherOfPearl_Recipe = new ConfigItem<bool>
        (
            "Void legendary: Mother Of Pearl",
            "Recipe enabled",
            "Should this item have a custom corruption recipe?",
            true
        );
        public static ConfigItem<string> MotherOfPearl_Ingredient1 = new ConfigItem<string>
        (
            "Void legendary: Mother Of Pearl",
            "Recipe ingredient 1",
            "First ingredient for corruption recipe",
            "BarrageOnBoss"
        );
        public static ConfigItem<string> MotherOfPearl_Ingredient2 = new ConfigItem<string>
        (
            "Void legendary: Mother Of Pearl",
            "Recipe ingredient 2",
            "Second ingredient for corruption recipe",
            "MissileVoid"
        );

        public GameObject OverwritePrefabMaterials()
        {
            GameObject ret = Main.Assets.LoadAsset<GameObject>("Assets/prefabs/motherOfPearl.prefab");

            Material[] materials =
            {
                material0,
                material1
            };
            ret.GetComponentInChildren<MeshRenderer>().SetMaterialArray(materials);

            return ret;
        }

        
        // Tokens
        public override void FormatDescriptionTokens()
        {
            string descriptionToken = ItemDef.descriptionToken;

            LanguageAPI.AddOverlay
            (
                descriptionToken,
                String.Format
                (
                    Language.currentLanguage.GetLocalizedStringByToken(descriptionToken),
                    MotherOfPearl_MissilesLaunched.Value,
                    MotherOfPearl_DamageCoeff.Value,
                    MotherOfPearl_DamageCoeffStack.Value,
                    MotherOfPearl_PickupConvert.Value * 100f
                )
            );
        }

        // Hooks
        public override void RegisterHooks()
        {
            // Add/remove behavior on inventory change
            On.RoR2.CharacterBody.OnInventoryChanged += (orig, self) =>
            {
                orig(self);

                MotherOfPearlBehavior behavior = self.GetComponent<MotherOfPearlBehavior>();
                int itemCount = GetItemCountEffective(self);

                if (GetItemCountEffective(self) > 0 && !behavior)
                {
                    behavior = self.AddItemBehavior<MotherOfPearlBehavior>(itemCount);
                    behavior.itemIndex = ItemIndex;
                    behavior.missiles = MotherOfPearl_MissilesLaunched.Value;
                    behavior.convertChance = MotherOfPearl_PickupConvert.Value;
                }

                if (behavior)
                {
                    behavior.stack = itemCount;
                    behavior.damageCoeff = (MotherOfPearl_DamageCoeff.Value + (MotherOfPearl_DamageCoeffStack.Value * (itemCount - 1))) / 100f;
                }

                if(GetItemCountEffective(self) <= 0 && behavior)
                {
                    UnityEngine.Object.Destroy(self.GetComponent<MotherOfPearlBehavior>());
                }
            };
            
            // Launch a missile
            On.RoR2.MoneyPickup.OnTriggerStay += (orig, self, other) =>
            {
                if (!NetworkServer.active || !self.alive)
                {
                    return;
                }

                TeamIndex objectTeam = TeamComponent.GetObjectTeam(other.gameObject);
                if (objectTeam == self.teamFilter.teamIndex && other.TryGetComponent(out CharacterBody body) && body.TryGetComponent(out MotherOfPearlBehavior behavior))
                {
                    behavior.Trigger();
                }

                orig(self, other);
            };
        }

        // Recipe
        public override void AddCorruptionRecipe()
        {
            if (MotherOfPearl_Recipe.Value == true)
            {
                ItemInit.MakeCorruptionRecipe
                (
                    MotherOfPearl_Ingredient1.Value,
                    MotherOfPearl_Ingredient2.Value,
                    ItemDef.name
                );
            }
        }

        // IDR
        public override ItemDisplayRuleDict AddItemDisplays()
        {
            GameObject ItemDisplayPrefab = Helpers.PrepareItemDisplayModel(PrefabAPI.InstantiateClone(itemPrefab, ItemDef.name + "Display", false));
            ItemDisplayRuleDict rules = new ItemDisplayRuleDict();

            #region IDR
            /*
            rules.Add("mdlCommandoDualies", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlHuntress", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlBandit2", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlToolbot", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlEngi", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlMage", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlMerc", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlTreebot", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlLoader", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlCroco", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlCaptain", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlRailGunner", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlVoidSurvivor", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlSeeker", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlFalseSon", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlChef", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlDroneTech", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            rules.Add("mdlDrifter", new RoR2.ItemDisplayRule[]{new RoR2.ItemDisplayRule{
                        ruleType = ItemDisplayRuleType.ParentedPrefab,
                        followerPrefab = ItemDisplayPrefab,
                        childName = "Pelvis",
                        localPos = new Vector3(0F, 0F, 0F),
                        localAngles = new Vector3(0F, 0F, 0F),
                        localScale = new Vector3(1F, 1F, 1F)
                    }
                }
            );
            */
            #endregion

            return rules;
        }
    }

    public class MotherOfPearlBehavior : CharacterBody.ItemBehavior
    {
        public ItemIndex itemIndex;
        public int missiles = 3;
        public float damageCoeff = 3f;
        public float convertRadius = 20f;
        public float convertChance = 10f;
        public float missileInterval = 0.1f;
        public float missileTimer = 0f;
        public float convertInterval = 0.33f;
        public float convertTimer = 0f;
        public int missileQueue = 0;

        public void Trigger()
        {
            missileQueue += missiles;
        }

        void FixedUpdate()
        {
            missileTimer += Time.fixedDeltaTime;
            convertTimer += Time.fixedDeltaTime;

            // Convert pickup
            if (convertTimer > convertInterval)
            {
                Collider[] colliders = Physics.OverlapSphere(body.transform.position, convertRadius);
                foreach(Collider collider in colliders)
                {
                    if (collider.gameObject)
                    {
                        GameObject gameObject = collider.gameObject;

                        if 
                        (
                            !gameObject.GetComponent<MotherOfPearlBlacklistBehavior>() &&
                            (
                                gameObject.GetComponentInChildren<AmmoPickup>() 
                                || gameObject.GetComponentInChildren<HealthPickup>() 
                                || gameObject.GetComponentInChildren<ElusiveAntlersPickup>()
                            ) 
                        )
                        {
                            if (CheckGoldPickupRoll())
                            {
                                SpawnGoldPickup(gameObject.transform.position);

                                EffectData effectData = new EffectData()
                                {
                                    origin = gameObject.transform.position
                                };
                                EffectManager.SpawnEffect(MotherOfPearl.convertEffectPrefab, effectData, true);

                                UnityEngine.Object.Destroy(gameObject);
                            }
                            else
                            {
                                gameObject.AddComponent<MotherOfPearlBlacklistBehavior>();
                            }
                        }
                    }
                }

                convertTimer = 0f;
            }

            // Missile launch
            if (missileTimer > missileInterval && missileQueue > 0)
            {
                MissileUtils.FireMissile
                (
                    body.corePosition,
                    body,
                    new ProcChainMask(),
                    null,
                    damageCoeff * body.damage,
                    body.RollCrit(),
                    GlobalEventManager.CommonAssets.missilePrefab,
                    DamageColorIndex.Item,
                    true
                );

                missileQueue--;
                missileTimer = 0f;
            }
        }

        public bool CheckGoldPickupRoll()
        {
            float totalRoll = 0f;

            var teamComponents = TeamComponent.GetTeamMembers(TeamIndex.Player);
            foreach (TeamComponent teamComponent in teamComponents)
            {
                if (teamComponent.body && teamComponent.body.inventory && teamComponent.body.inventory.GetItemCountEffective(itemIndex) > 0)
                {
                    totalRoll += convertChance * 100f;
                }
            }

            return Util.CheckRoll(totalRoll);
        }

        public void SpawnGoldPickup(Vector3 position)
        {
            GameObject gameObject = UnityEngine.Object.Instantiate(MotherOfPearl.moneyPackPrefab, position, UnityEngine.Random.rotation);
            if ((bool)gameObject)
            {
                Collider component = gameObject.GetComponent<Collider>();
                Physics.IgnoreCollision(component, gameObject.GetComponent<Collider>());
                TeamFilter component2 = gameObject.GetComponent<TeamFilter>();
                if ((bool)component2)
                {
                    component2.teamIndex = TeamIndex.Player;
                }
                MoneyPickup componentInChildren = gameObject.GetComponentInChildren<MoneyPickup>();
                if ((bool)componentInChildren)
                {
                    componentInChildren.baseGoldReward = 25;
                    Physics.IgnoreCollision(component, componentInChildren.GetComponent<Collider>());
                }
                GravitatePickup componentInChildren2 = gameObject.GetComponentInChildren<GravitatePickup>();
                if ((bool)componentInChildren2)
                {
                    Physics.IgnoreCollision(component, componentInChildren2.GetComponent<Collider>());
                }
                gameObject.transform.localScale = Vector3.one * 1f;
                NetworkServer.Spawn(gameObject);
            }
        }
    }

    public class MotherOfPearlBlacklistBehavior : MonoBehaviour
    {
        
    }
}